create table if not exists public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    username text not null unique,
    coins integer not null default 0 check (coins >= 0),
    character jsonb not null default '{"inventory": [], "equipped": {"shirt": "#4caf50", "hair": "#4b2e1f", "accessory": ""}}'::jsonb,
    role text not null default 'user' check (role in ('user', 'admin')),
    created_at timestamptz not null default now()
);

create table if not exists public.announcements (
    id bigint generated by default as identity primary key,
    message text not null,
    created_by uuid not null references public.profiles(id),
    created_at timestamptz not null default now()
);

create table if not exists public.game_events (
    id boolean primary key default true check (id),
    coin_rain_active boolean not null default false,
    multiplier integer not null default 1 check (multiplier in (1, 2, 4, 10, 20, 100)),
    updated_at timestamptz not null default now(),
    updated_by uuid references public.profiles(id)
);

insert into public.game_events (id) values (true) on conflict (id) do nothing;

alter table public.profiles enable row level security;
alter table public.announcements enable row level security;
alter table public.game_events enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
as $$
    select exists (
        select 1 from public.profiles
        where id = auth.uid() and role = 'admin'
    );
$$;

grant execute on function public.is_admin() to authenticated;

grant select, update on public.profiles to authenticated;
grant select on public.announcements, public.game_events to authenticated;

grant usage, select on all sequences in schema public to authenticated;

create policy "Users can read profiles"
on public.profiles for select to authenticated using (true);

create policy "Users can update their character"
on public.profiles for update to authenticated
using (id = auth.uid())
with check (id = auth.uid());

create policy "Everyone can read announcements"
on public.announcements for select to authenticated using (true);

create policy "Admins can create announcements"
on public.announcements for insert to authenticated
with check (public.is_admin() and created_by = auth.uid());

create policy "Everyone can read game events"
on public.game_events for select to authenticated using (true);

create or replace function public.add_coins(target_user uuid, amount integer)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
    if not public.is_admin() or amount < 1 then
        raise exception 'Not allowed';
    end if;
    update public.profiles set coins = coins + amount where id = target_user;
end;
$$;

grant execute on function public.add_coins(uuid, integer) to authenticated;

create or replace function public.set_game_event(coin_rain boolean, new_multiplier integer)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
    if not public.is_admin() or new_multiplier not in (1, 2, 4, 10, 20, 100) then
        raise exception 'Not allowed';
    end if;
    update public.game_events
    set coin_rain_active = coin_rain, multiplier = new_multiplier,
        updated_at = now(), updated_by = auth.uid()
    where id = true;
end;
$$;

grant execute on function public.set_game_event(boolean, integer) to authenticated;

create or replace function public.claim_coin_rain()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
    if exists (select 1 from public.game_events where id = true and coin_rain_active) then
        update public.profiles set coins = coins + 5 where id = auth.uid();
    else
        raise exception 'Coin rain is not active';
    end if;
end;
$$;

grant execute on function public.claim_coin_rain() to authenticated;

create or replace function public.claim_correct_answer()
returns void
language plpgsql
security definer
set search_path = public
as $$
 declare reward integer;
begin
    select multiplier into reward from public.game_events where id = true;
    update public.profiles set coins = coins + coalesce(reward, 1) where id = auth.uid();
end;
$$;

grant execute on function public.claim_correct_answer() to authenticated;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
    insert into public.profiles (id, username)
    values (new.id, coalesce(new.raw_user_meta_data ->> 'username', split_part(new.email, '@', 1)));
    return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Run this once after registering the admin account.
-- update public.profiles set role = 'admin' where username = 'CyberTimo1234';

alter publication supabase_realtime add table public.profiles;
alter publication supabase_realtime add table public.announcements;
alter publication supabase_realtime add table public.game_events;
